name: Deploy Web
on:
  push:
    branches:
      - main
jobs:
  build_and_push:
    name: Build and Push
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      contents: read
      packages: write
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push API
        uses: docker/build-push-action@v5
        with:
          build-args: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          file: Dockerfile
          push: true
          tags: ghcr.io/rsametsamyeli/samyeli-dev:latest

  deploy:
    name: Deploy to Dokku
    runs-on: ubuntu-latest
    needs: build_and_push
    environment: test
    steps:
      - name: Deploy to Dokku
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST_IP }}
          username: root
          key: ${{ secrets.HOST_SSH_KEY }}
          script: |
            docker pull ghcr.io/rsametsamyeli/samyeli-dev:latest
            dokku ps:rebuild samyeli.dev
            yes | docker image prune --filter="label=app=samyeli.dev"